# Generated by Django 5.0.8 on 2024-08-13 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geenfy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='texto',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='titulo',
            field=models.CharField(default='sem titulo', max_length=55),
        ),
    ]
