# Generated by Django 5.0.8 on 2024-08-13 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geenfy', '0002_homepage_texto_homepage_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='titulo',
            field=models.CharField(max_length=55),
        ),
    ]
