# Generated by Django 5.0.8 on 2024-08-13 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geenfy', '0003_alter_homepage_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
