# Generated by Django 5.0.8 on 2024-08-13 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geenfy', '0004_alter_homepage_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='texto',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='titulo',
            field=models.CharField(max_length=55),
        ),
    ]
