# Generated by Django 5.0.8 on 2024-08-13 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geenfy', '0006_login_alter_homepage_texto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='texto',
            field=models.CharField(max_length=200),
        ),
    ]
