# Generated by Django 5.0.8 on 2024-08-20 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geenfy', '0007_alter_homepage_texto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='imgLog',
            new_name='imgLogin',
        ),
    ]
