# Generated by Django 5.0.8 on 2024-08-20 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geenfy', '0008_rename_imglog_login_imglogin'),
    ]

    operations = [
        migrations.CreateModel(
            name='NovaTurma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=55)),
                ('texto', models.CharField(max_length=100)),
                ('imgNovaTurma', models.ImageField(upload_to='imgNovaTurma/')),
            ],
        ),
    ]
