# Generated by Django 5.0.8 on 2024-08-27 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geenfy', '0009_novaturma'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=55)),
                ('imgCadastro', models.ImageField(upload_to='imgCadastro/')),
            ],
        ),
    ]
