# Generated by Django 5.0.8 on 2024-09-10 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geenfy', '0013_funcionarios_usuario'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Funcionarios',
            new_name='Funcionario',
        ),
    ]
