# Generated by Django 5.0.8 on 2024-09-12 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geenfy', '0014_rename_funcionarios_funcionario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finished_file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquino_fineshed', models.FileField(upload_to='finished_files/')),
            ],
        ),
        migrations.CreateModel(
            name='In_progress_file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo_inprogress', models.FileField(upload_to='in_progress_files/')),
            ],
        ),
    ]
