# Generated by Django 5.0.8 on 2024-09-19 17:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geenfy', '0017_perfileditar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finished_file',
            old_name='arquino_fineshed',
            new_name='arquivo_fineshed',
        ),
        migrations.AddField(
            model_name='finished_file',
            name='turma',
            field=models.CharField(default='desconhecido', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='finished_file',
            name='upload_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='in_progress_file',
            name='turma',
            field=models.CharField(default='desconhecido', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='in_progress_file',
            name='upload_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
