# Generated by Django 5.0.8 on 2024-09-24 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geenfy', '0019_cadastro_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='login_CAF',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='login_IHX',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='senha_CAF',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='senha_IHX',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
