# Generated by Django 5.0.8 on 2024-09-24 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geenfy', '0020_alter_usuario_login_caf_alter_usuario_login_ihx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='user',
            new_name='nome',
        ),
    ]
