# Generated by Django 5.0.8 on 2024-09-24 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geenfy', '0021_rename_user_usuario_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='nome',
            new_name='user',
        ),
    ]
