# Generated by Django 5.0.8 on 2024-09-26 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geenfy', '0022_rename_nome_usuario_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='login_CAF',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='login_IHX',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='senha_CAF',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='senha_IHX',
            field=models.CharField(max_length=30),
        ),
    ]
