# Generated by Django 5.0.8 on 2024-09-26 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geenfy', '0023_alter_usuario_login_caf_alter_usuario_login_ihx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='in_progress_file',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Em Progresso', 'Em Progresso')], default='Pendente', max_length=15),
        ),
    ]
