# Generated by Django 5.0.8 on 2024-10-29 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geenfy', '0024_in_progress_file_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lixeira',
            new_name='Storage',
        ),
    ]
