# Generated by Django 5.0.8 on 2024-10-29 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geenfy', '0025_rename_lixeira_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='senha_CAF',
            field=models.CharField(max_length=30),
        ),
    ]
